name: Basic tests

on: [push, pull_request]

jobs:
  test_pins:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: pip install -r tests/requirements.txt
      - run: pytest -k test_has_at_most_one_pinned_dependency

  test_install:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        os: [ 'windows-latest', 'macos-latest', 'ubuntu-latest' ]
        python: [ '3.7', '3.8', '3.9', '3.10', '3.11' ]
        arch: [ 'x64', 'x86' ]
        exclude:
          - os: macos-latest
            arch: x86
          - os: ubuntu-latest
            arch: x86

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
          architecture: ${{ matrix.arch }}

      - name: Install oldest Numpy
        run: pip install . --only-binary numpy

      - name: Install test dependencies
        run: pip install -r tests/requirements.txt

      - name: Test valid numpy installed
        run: pytest tests/test_installation.py -k test_valid_numpy_is_installed
